### PR TITLE
feat: edit profile and updated post functionality

### PR DESCRIPTION
**Pull request by nmrchvz**
### Added to post functionality:
- imported ckeditor for common mark input
- ckeditor allows for markdown, embedded images (by URL source and not uploading), or even just plaintext
- added a tag button that allows adding tags more easier
- changed uploaded images to be not required to submit a post
- local author's now have a post activity stream on their profile showing all of their posts (Public, Friends, Private)

image

<hr>

### Changed how post visibility works:
- public and friends don't need a recipient uuid or unlisted option
- private posts are assumed to be unlisted and can be a DM to another local author (might need to change this if you want to DM a remote author as the select option queries only from local authors).
- if an local author wants to make just a embedded image as the post and nothing else, then visibility has to be private to author, recipient uuid empty (or themselves), and unlisted checkbox is true.
- unlisted posts will always be visible their own post activity stream on their profile

image

image

<hr>

### Added edit profile functionality:
- local users are allowed to change their username, first/last name, email, and password
- changing password directs them to a password change page

image

image

<hr>

Assumptions:
- content type would have to be manually changed to whichever the author wants the post content to be (plaintext, markdown, base64, image as png/jpeg)
- tags/catagories could be anything like random numbers/symbols (probably wouldn't like a tag with double quotations or double brackets)
- by default, ckeditor is in markdown; and if content type is plaintext then post will be rendered as raw markdown
- if an author wanted plaintext as the post content they would have to manually change to source text in the ckeditor
image
- if an author just wanted a post of an unlisted embedded image they would have to upload their image, and select visibility to `Private to Author (DM)` and recipient uuid can be themselves or nothing. If they wanted to revisit their unlisted post, they can access it in their post activity stream

### CODE REVIEW

**Comment by Tardnicus** [comment]
How are you handling multiple embedded images? Are you making multiple unlisted posts, like Abram suggests? Or are you serving them statically using Pillow?

I ask because I recently switched out the static hosting for images to base64 so that information could be stored as an object in the database.

**Comment by nmrchvz** [comment]
@Tardnicus 
> How are you handling multiple embedded images? Are you making multiple unlisted posts, like Abram suggests? Or are you serving them statically using Pillow?

Currently, images that are uploaded or image hosted are, as you stated, 
> static hosting for images to base64 so that information could be stored as an object in the database. 

Posts are limited to only one uploaded image (that is converted to base64) and doesn't have multiple embedded image handling. If the an author wanted multiple embedded images in a unlisted post then multiple separate unlisted posts have to be made.

Images that are link/references to other websites can have multiple images (as it just stores its image URL) within its post and is not split into multiple posts. 

Example of markdown multiple images:
image

**Comment by nmrchvz** [comment]
Ahh I see what you mean in Abram's reply here https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1823875#p4788368
Do you think multiple embedded images should be changed then?

**Comment by Tardnicus** [comment]
Sorry for the late reply, I was and am still a bit busy yesterday/today.

I think hosting the images is a better idea, overall, and i only mentioned it because that's what Abram kept saying. I do admit that hosting makes it muuch easier to embed.

The only annoyance is that the static director gets cleared on Heroku when there is a new build of the app

**Review by Tardnicus — APPROVED** [review]
I don't have a chance to go through the code with a fine-toothed comb but from a preliminary look it seems fine!

as long as you've tested it with the upstream changes than it's all good

**Pull request merged**
